#!/bin/bash
# Copyright (c) 2018 Matt Struble

RANDOM=$$$(date +%s)

FACES=("owo" "UwU" ">w<" "^w^")

usage() {
	echo "usage: git owo owoer -m <message>"
	echo 
}

owoText() {
	local val="$@"
	val=$(echo $val | \
		sed -e 's/\(r\|l\)/w/g' \
		-e 's/\(R\|L\)/W/g' \
		-e 's/n\([aeiou]\)/ny\1/g' \
		-e 's/N\([aeiou]\)/Ny\1/g' \
		-e 's/N\([AEIOU]\)/Ny\1/g' \
		-e 's/ove/uv/g' \
		-e "s/\!\+/\ ${FACES[$RANDOM % ${#FACES[@]} ]}/g")

	# "Return" the value passed in
	echo "$val"
}

cmd_owoer() {
	if [ "$#" -lt 2 ]; then 
		usage; exit 1
	fi

	while getopts ":m:" opt; do
		case "${opt}" in 
			m)
				owoText ${OPTARG}
				;;
			*)
				usage
				;;
		esac 
	done 
}
