#!/usr/bin/env sh

usage() {
	echo "usage: git owo commit [options]"
	echo
}

cmd_commit() {
	if [ "$#" -lt 2 ]; then 
		usage; exit 1
	fi
	
	workingdir=$0
	
	str=""
	isM=0
	for var in "$@"
	do
		if [ $isM -eq 1 ]; then 
			# todo: translate
			echo "translate"
			isM=0
		fi

		if [ "$var" = "-m" ]; then
			echo "ism"
			isM=1
		fi
		echo $var
		str="$str $var"
	done
	echo $str
#	git commit $str	
}
