#!/bin/bash

usage() {
	echo "usage: git owo commit [options]"
	echo
}

cmd_commit() {
	if [ "$#" -lt 2 ]; then 
		usage; exit 1
	fi
	
	workingdir=$0
	
	. "./git-owo-owoer"

	str=""
	isM=0
	for var in "$@"
	do
		if [ $isM -eq 1 ]; then 
			var="$(translateText "$var")"
			isM=0
		fi

		if [ "$var" = "-m" ]; then
			isM=1
		fi
		str="$str$var "
	done
	opt=("$str")
	git commit "${opt[@]}"	
}
